### ISSUE TITLE
zeal crashed when the configured proxy itself couldn't connect

### ISSUE THREAD

**Issue by djndl1** [zealdocs/zeal#1100]
I configured a local http proxy in zeal, which was provided by privoxy, which in turn just forwarded traffic from another SOCKS5 proxy, since zeal doesn't support SOCKS5. After the SOCKS5 proxy itself failed to connect to the outer network (both the proxies were still running), zeal kept crashing whenever it tried to connect to the server to update the docset list. It returned to normal after I switched off any proxy configuration.
```
Application: zeal (zeal), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f6939f5d900 (LWP 17099))]

Thread 9 (Thread 0x7f68e3ffd700 (LWP 17201)):
#0  0x00007f6941b4300c in futex_wait_cancelable (private=0, expected=0, futex_word=0x7f69395f1988) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007f6941b4300c in __pthread_cond_wait_common (abstime=0x0, mutex=0x7f69395f1938, cond=0x7f69395f1960) at pthread_cond_wait.c:502
#2  0x00007f6941b4300c in __pthread_cond_wait (cond=0x7f69395f1960, mutex=0x7f69395f1938) at pthread_cond_wait.c:655
#3  0x00007f6941f6c3bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f6942e9f160 in  () at /lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f6942e9d942 in  () at /lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f6942e9da16 in  () at /lib/x86_64-linux-gnu/libQt5WebKit.so.5
#7  0x00007f6942ea1918 in  () at /lib/x86_64-linux-gnu/libQt5WebKit.so.5
#8  0x00007f6942ec5fea in  () at /lib/x86_64-linux-gnu/libQt5WebKit.so.5
#9  0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#10 0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7f68e1112700 (LWP 17164)):
[KCrash Handler]
#6  0x00007f69456b3ba4 in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#7  0x00007f69456b2c69 in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#8  0x00007f6946109182 in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f69464cf4b1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007f69464d6950 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007f69460df5a9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f69460e259b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f6946131233 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f6941302f2e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f69413031c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f694130325c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f6946130863 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f69460de27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f6945f2dec6 in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f6945f37aa7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#22 0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f6929729700 (LWP 17106)):
#0  0x00007f6946130783 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007f6941302669 in g_main_context_prepare () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f694130306b in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f694130325c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f694613087b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f69460de27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f6945f2dec6 in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f6945f37aa7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f6929f2a700 (LWP 17105)):
#0  0x00007f694134ce84 in g_mutex_unlock () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f694130265c in g_main_context_prepare () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f694130306b in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f694130325c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f694613087b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f69460de27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f6945f2dec6 in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f6945f37aa7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f692a7c5700 (LWP 17104)):
#0  0x00007f6941c44819 in __GI___poll (fds=0x7f68dc0025e0, nfds=1, timeout=9326) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6941303136 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f694130325c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f694613087b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f69460de27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f6945f2dec6 in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f6945f37aa7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f69315f1700 (LWP 17103)):
#0  0x00007f694130324f in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f694613087b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f69460de27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f6945f2dec6 in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f693964b545 in  () at /lib/x86_64-linux-gnu/libQt5DBus.so.5
#5  0x00007f6945f37aa7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f6933ee1700 (LWP 17102)):
#0  0x00007f6941c44819 in __GI___poll (fds=0x7f6933ee0bb8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6944e77cf7 in  () at /lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f6944e7991a in xcb_wait_for_event () at /lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f6938ce1d79 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f6945f37aa7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f6939f59700 (LWP 17101)):
#0  0x00007f6941b4300c in futex_wait_cancelable (private=0, expected=0, futex_word=0x7f6944e0b154) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007f6941b4300c in __pthread_cond_wait_common (abstime=0x0, mutex=0x55e00c81c920, cond=0x7f6944e0b128) at pthread_cond_wait.c:502
#2  0x00007f6941b4300c in __pthread_cond_wait (cond=0x7f6944e0b128, mutex=0x55e00c81c920) at pthread_cond_wait.c:655
#3  0x00007f6941f6c3bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f6944336542 in  () at /lib/x86_64-linux-gnu/libQt5WebKit.so.5
#5  0x00007f6944336659 in  () at /lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x00007f6941f71b2f in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f6941b3cfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007f6941c4f4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f6939f5d900 (LWP 17099)):
#0  0x00007f6941c44819 in __GI___poll (fds=0x55e00cb91930, nfds=1, timeout=19338) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6941303136 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f694130325c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f694613087b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f6938d783e1 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#5  0x00007f69460de27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f69466b9e9d in QDialog::exec() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x000055e00c691996 in  ()
#8  0x000055e00c69cab3 in  ()
#9  0x000055e00c69c383 in  ()
#10 0x000055e00c69b843 in  ()
#11 0x00007f6946108a43 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f69464c8f02 in QAction::triggered(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f69464cb510 in QAction::activate(QAction::ActionEvent) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f694663ba7c in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f6946642fa0 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f6946643f2b in QMenu::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f694650d588 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f694664638b in QMenu::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f69464cf4b1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f69464d6b98 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f69460df5a9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f69464d5ec9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f69465283d3 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f694652ab9e in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f69464cf4b1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f69464d6950 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007f69460df5a9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007f69458d9fe3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#29 0x00007f69458dbe25 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#30 0x00007f69458b606b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#31 0x00007f6938d783eb in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#32 0x00007f69460de27b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007f69460e6262 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x000055e00c67e695 in  ()
#35 0x00007f6941b7a09b in __libc_start_main (main=0x55e00c67db82, argc=1, argv=0x7ffde7fc5bb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffde7fc5ba8) at ../csu/libc-start.c:308
#36 0x000055e00c67ca9a in  ()
[Inferior 1 (process 17099) detached]
```
```
zeal.core.applicationsingleton: Singleton ID: Cq_LEwSs9FKYgI7TilfgRS3UNMAFbnGRP9o5k_mOeI4
zeal.core.applicationsingleton: Starting as a primary instance. (PID: 17099)
libpng warning: iCCP: known incorrect sRGB profile
Empty filename passed to function
Empty filename passed to function
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = zeal path = /usr/local/bin pid = 17099
KCrash: Arguments: /usr/local/bin/zeal 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QSocketNotifier: Invalid socket 14 and type 'Read', disabling...
QSocketNotifier: Invalid socket 39 and type 'Read', disabling...
QSocketNotifier: Invalid socket 9 and type 'Read', disabling...
QSocketNotifier: Invalid socket 28 and type 'Read', disabling...
The X11 connection broke (error 1). Did the X11 server die?

[1]+  Exit 1                  zeal
```

**Comment by trollixx** [comment]
I don't see zeal itself in any of the stack traces, will try to reproduce...

**Comment by trollixx** [comment]
Zeal 0.7.0 will support SOCKS5 proxies (#893), I can't reproduce the crash with the recent build from master. So I assume the problem is fixed.
