### ISSUE TITLE
gendocsets/qt5 not working

### ISSUE THREAD

**Issue by Ramblurr** [zealdocs/zeal#234]
With a fresh checkout from master, building the Qt5 docs doesn't work. It's not downloading all the docs.

```
➜  qt5 git:(master) ✗ bash download.sh
--2014-12-05 10:56:19--  http://qt-project.org/doc/qt-5.0/qtdoc/index.html
Resolving qt-project.org (qt-project.org)... 87.238.53.172
Connecting to qt-project.org (qt-project.org)|87.238.53.172|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://qt-project.org/doc/qt-5/index.html [following]
--2014-12-05 10:56:20--  http://qt-project.org/doc/qt-5/index.html
Reusing existing connection to qt-project.org:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘qtdoc/index.html’

qtdoc/index.html                                    [  <=>                                                                                                    ]  28.35K  85.6KB/s   in 0.3s

2014-12-05 10:56:20 (85.6 KB/s) - ‘qtdoc/index.html’ saved [29027]

FINISHED --2014-12-05 10:56:20--
Total wall clock time: 0.8s
Downloaded: 1 files, 28K in 0.3s (85.6 KB/s)
Converting qtdoc/index.html... 7-56
Converted 1 files in 0.002 seconds.
➜  qt5 git:(master) ✗ python crawl.py
Traceback (most recent call last):
  File "crawl.py", line 13, in <module>
    tree = parse('qtdoc/modules.html')
  File "/usr/lib64/python2.7/site-packages/lxml/html/__init__.py", line 769, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:70175)
  File "parser.pxi", line 1749, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102290)
  File "parser.pxi", line 1775, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:102554)
  File "parser.pxi", line 1679, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:101589)
  File "parser.pxi", line 1110, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:97041)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91494)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92680)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91941)
IOError: Error reading file 'qtdoc/modules.html': failed to load external entity "qtdoc/modules.html"
```

**Comment by trollixx** [comment]
We've dropped support for custom Zeal format of docsets. Use Dash [instructions](http://kapeli.com/docsets) to generate docsets.
